export const INJECTION_TOKENS = {
  COOMB_AI_CLIENT_PORT: "COOMB_AI_CLIENT_PORT",
  COOMB_AI_CLIENT: "COOMB_AI_CLIENT",
  USER_REPOSITORY_PORT: "USER_REPOSITORY_PORT",
  RESUME_REPOSITORY_PORT: "RESUME_REPOSITORY_PORT",
  CHAT_REPOSITORY_PORT: "CHAT_REPOSITORY_PORT",
  MESSAGE_REPOSITORY_PORT: "MESSAGE_REPOSITORY_PORT",
  GENERATED_RESUME_REPOSITORY_PORT: "GENERATED_RESUME_REPOSITORY_PORT",
  LLM_PROVIDER: "LLM_PROVIDER",
} as const;

export type InjectionToken = typeof INJECTION_TOKENS[keyof typeof INJECTION_TOKENS];


